name: appointment_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8       # iOS-style icons
  flutter_svg: ^2.2.2            # Display SVG images
  flutter_screenutil: ^5.9.3     # Responsive UI scaling

  # State Management
  flutter_bloc: ^9.1.1           # Bloc state management

  # Localization
  easy_localization: ^3.0.8      # Multi-language support

  # Networking
  dio: ^5.9.0                    # HTTP client
  pretty_dio_logger: ^1.4.0     # Logs API requests nicely
  retrofit: ^4.9.1              # API generator wrapper for Dio

  # Dependency Injection
  get_it: ^9.0.5                # Service locator

  # Date & formatting
  intl: ^0.20.2                 # Date/number formatting

  # Code Annotations (needed in runtime)
  json_annotation: ^4.9.0       # Needed for json_serializable
  freezed_annotation: ^3.1.0    # Annotations used by Freezed
  firebase_core: ^4.3.0

dev_dependencies:
  # Flutter Tools
  flutter_lints: ^5.0.0          # Recommended lint rules
  flutter_test:
    sdk: flutter                 # Testing framework

  # Code Generation Tools
  build_runner: ^2.10.4           # Runs code generators
  json_serializable: ^6.11.1      # Generates JSON mapping code
  retrofit_generator: ^10.1.4     # Generates Retrofit API code
  freezed: ^3.2.3                 # Generates immutable classes using Freezed

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
