# # This file contains the fastlane.tools configuration
# # You can find the documentation at https://docs.fastlane.tools
# #
# # For a list of all available actions, check out
# #
# #     https://docs.fastlane.tools/actions
# #
# # For a list of all available plugins, check out
# #
# #     https://docs.fastlane.tools/plugins/available-plugins
# #

# # Uncomment the line if you want fastlane to automatically update itself
# # update_fastlane

# default_platform(:android)

# platform :android do
#   desc "Runs all the tests"
#   lane :test do
#     gradle(task: "test")
#   end

#   desc "Submit a new Beta Build to Crashlytics Beta"
#   lane :beta do
#     gradle(task: "clean assembleRelease")
#     crashlytics
  
#     # sh "your_script.sh"
#     # You can also use other beta testing services here
#   end

#   desc "Deploy a new version to the Google Play"
#   lane :deploy do
#     gradle(task: "clean assembleRelease")
#     upload_to_play_store
#   end
# end
default_platform(:android)

platform :android do
  lane :distribute_firebase do |options|
    flavor = options[:flavor]
    app_id = options[:app_id]

    main_file =
      flavor == "production" ? "lib/main_production.dart" : "lib/main_development.dart"

    sh("flutter build apk --flavor #{flavor} -t #{main_file} --release")

    firebase_app_distribution(
      app: app_id,
      service_credentials_file: "android/service-account.json",
      testers: "ahmed125abdelkrim@gmail.com",
      release_notes: "Automated build for #{flavor}",
      apk_path: "../build/app/outputs/flutter-apk/app-#{flavor}-release.apk"
    )
  end
end

