# # This file contains the fastlane.tools configuration
# # You can find the documentation at https://docs.fastlane.tools
# #
# # For a list of all available actions, check out
# #
# #     https://docs.fastlane.tools/actions
# #
# # For a list of all available plugins, check out
# #
# #     https://docs.fastlane.tools/plugins/available-plugins
# #

# # Uncomment the line if you want fastlane to automatically update itself
# # update_fastlane

# default_platform(:android)

# platform :android do
#   desc "Runs all the tests"
#   lane :test do
#     gradle(task: "test")
#   end

#   desc "Submit a new Beta Build to Crashlytics Beta"
#   lane :beta do
#     gradle(task: "clean assembleRelease")
#     crashlytics
  
#     # sh "your_script.sh"
#     # You can also use other beta testing services here
#   end

#   desc "Deploy a new version to the Google Play"
#   lane :deploy do
#     gradle(task: "clean assembleRelease")
#     upload_to_play_store
#   end
# end
default_platform(:android)

platform :android do
  desc "Build APK and upload to Firebase App Distribution"
  lane :distribute_firebase do

    # Build production APK
    sh("flutter build apk --flavor production -t lib/main_production.dart --release")

    # Upload APK to Firebase
    firebase_app_distribution(
      app: "1:367726199888:android:527cef7bcb7c8e81d17d55",
      testers: "ahmed125abdelkrim@gmail.com",
      release_notes: "Production build",
      apk_path: "../build/app/outputs/flutter-apk/app-production-release.apk"
    )
  end
end
