default_platform(:android)

platform :android do
  lane :distribute_firebase do |options|
    flavor = options[:flavor]
    app_id = options[:app_id]
    main_file = flavor == "production" ? "lib/main_production.dart" : "lib/main_development.dart"

    sh("cd .. && flutter build apk --flavor #{flavor} -t #{main_file} --release")

    firebase_app_distribution(
      app: app_id,
      service_credentials_file: "service-account.json",
      testers: "ahmed125abdelkrim@gmail.com",
      release_notes: "Automated build for #{flavor}",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-#{flavor}-release.apk"
    )
  end
end